apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: config-server
spec:
  maxReplicas: 30
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: config-server
  targetCPUUtilizationPercentage: 50