apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: config-server
spec:
  maxReplicas: 20
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: config-server
  targetCPUUtilizationPercentage: 50