apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
  name: config-server-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: app-port
    port: 1010
    protocol: TCP
    targetPort: 2020
  selector:
    app: config-server
    in-service: "true"
  sessionAffinity: None
  type: NodePort