apiVersion: v1
kind: ConfigMap
metadata:
    name: edd-config-server-configs
data:
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "b-1.edd-kafka.uqgo0j.c4.kafka.us-east-2.amazonaws.com:9092,b-4.edd-kafka.uqgo0j.c4.kafka.us-east-2.amazonaws.com:9092,b-2.edd-kafka.uqgo0j.c4.kafka.us-east-2.amazonaws.com:9092"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES: "z-2.edd-kafka.uqgo0j.c4.kafka.us-east-2.amazonaws.com:2181,z-3.edd-kafka.uqgo0j.c4.kafka.us-east-2.amazonaws.com:2181,z-1.edd-kafka.uqgo0j.c4.kafka.us-east-2.amazonaws.com:2181"