apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cart-service
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-service
  targetCPUUtilizationPercentage: 50